### ISSUE TITLE
Attempted to divide by zero error when creating a sprite with only one texture

### ISSUE THREAD

**Issue by chesiren** [Facepunch/sbox-spritetools#10]
This error seems to only happens when i make a sprite with only one frame

How to reproduce:
- Add an image to the project
- Right click on it, Create 2D sprite then save
- Then try to drag and drop onto the scene
- `Error when dropping [SpriteTools.SpriteDropObject](arg:0) - Attempted to divide by zero.`

**Comment by CarsonKompon** [comment]
This should be fixed now. Let me know if you have any other issues with it :)
