### ISSUE TITLE
The variable 'e' is declared but never used

### ISSUE THREAD

**Issue by chesiren** [Facepunch/sbox-spritetools#11]
It's just an unused exception try catch, it doesn't break anything but it would be nice if that catch was properly handled so we don't get a warning

in TextureAtlas:

https://github.com/Facepunch/sbox-spritetools/blob/2ac8da6aac9ce7cd16ef8957ae889abcddd059ec/Libraries/SpriteTools/Code/TextureAtlas.cs#L201

**Comment by CarsonKompon** [comment]
I have this solved in the tileset branch and hope to have that merged this week :)
