### ISSUE TITLE
Tile position randomly going to negative max int causing overflow 

### ISSUE THREAD

**Issue by cs716** [Facepunch/sbox-spritetools#18]
```
Exception when calling 'Start' on TilesetComponent on (Tileset)
System.OverflowException: Arithmetic operation resulted in an overflow.
   at DMD<System.Void SpriteTools.TilesetComponent:RebuildMesh()>(TilesetComponent this)
   at SpriteTools.TilesetComponent.OnStart()
   at Sandbox.Component.ExceptionWrap(String name, Action a)
```

I added a debug line to output  all of my tile positions and noticed one way out of bounds. This happened twice even after deleting my tile component and re-making the level. 
![image](https://github.com/user-attachments/assets/77d5cc7b-3386-46a8-a57d-9f3eaca6ceb2)
(info from the for loop in collisionLayer.Tiles) 
`Log.Info( Vector2Int.Parse( tile.Key ) );`

I added a bandaid fix locally by having it ignore tiles above 100k to avoid the overflow. I am not sure how a tile is being placed that far out.

**Comment by CarsonKompon** [comment]
This happens if you accidentally click to place a tile when you're in the 3D view. I need to make that trace hit the grid plane

**Comment by cs716** [comment]
There might be some other way to cause it. I never leave the 2D view now. Not sure if it matters or if it was a coincidence but this happened to me most recently when I tried to use the line tool to paint one tile.

**Comment by CarsonKompon** [comment]
Should be good in the latest version/commit. You were right about line/rect tool painting one tile
