### ISSUE TITLE
Display file name when hovering/selected over frame

### ISSUE THREAD

**Issue by bakscratch** [Facepunch/sbox-spritetools#4]
Display file name on hovered.
![image](https://github.com/CarsonKompon/sprite_tools/assets/8184184/d4fdf17e-58a5-491d-989d-88922a64ba56)

**Comment by CarsonKompon** [comment]
I like this. I will do this after I get spritesheet importing in since that might change some structure.

**Comment by CarsonKompon** [comment]
Now that the spritesheet stuff is in I've added this. Displays frame number, file name, and rect (if part of a spritesheet)

![image](https://github.com/Facepunch/sbox-spritetools/assets/5159369/cf2c3275-dea4-40a8-a6c8-f633ce3a4b63)

![image](https://github.com/Facepunch/sbox-spritetools/assets/5159369/0b862411-0dea-4df8-b38d-66e899346ecc)
